// --- ⭐️ الخطوة 1: تعريف هوية الأدمن الرئيسي ⭐️ ---
// !!! اكتب إيميلك اللي هتسجل بيه أول مرة هنا !!!
// ... existing code ... -->
// ----------------------------------------------------

// --- ⭐️ الخطوة 3: تعريف المتغيرات الأساسية ⭐️ ---
const appId = "my-order-tracker"; // اسم ثابت للتطبيق (لا تغيره)
// ----------------------------------------------------

// --- ⭐️ الخطوة 4: ملف الخط العربي (Amiri) لـ PDF ⭐️ ---
// هذا متغير كبير يحتوي على الخط لضمان طباعة العربية بشكل سليم
const amiriFontBase64 = 'AAEAAAARAQAABAAQRFNJRwAAAAAAowAAACsAAAAoR0RFRgAAAAABHAAAABwAAAAcR0dQT1MAAAAAARwAAAAOAAAAQEdTVUIAAAAAASAAAAAIAAAACE9TLzIAAAABDAAAAFgAAABgY21hcAAAAAEsAAAAvAAAAMBiZWFkAAABMAAAADYAAAA2aGhlYQAAATQAAAAgAAAAJGhtdHgAAAEYAAAAGAAAABxtYXhwAAABJAAAABgAAAAgbmFtZQAAASwAAAIHAAAIa3Bvc3QAAAMMAAAAZAAAAGBwcmVwAAADeAAAACAAAAAgZ2FzcAAAAOAAAAAIAAAACAAAABEAAAAAAEwBAAACgAUAAGwAIAAAABQAAgNGAQAAAAEAAAAAwL8AfQAAAADBXwB9AAAAAAABA5gDvgNCAIAAFQAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAEAABNBLAIAAQAAEwAAAAIAAQADAAEAAAAAAAIAAgAWAAUAAQOaBCAAUAAEgAAAAAABTQJYIAAAAAAAAwDoAUQAAAAAAAAAAAAAAIAAAgAAAAAAAAAAACgAAAQAAAAAAAAABAAEAAAAAAABCAAEAAAAAAAIAAwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAAAAgAcAAEAAAAAAAIAAwAIAAAAAAACAAoADgAAAAAACQABAIAAAAAAAAAAAAAIAEAAVAAAAAAAAABAAwAAAEAAAAAAAEABQAAAAEAAAAAAAIABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAFAAAAAQAAAAAAAkABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAABAAEAASQAAAAAAAAABAAEAAAAAAABCAAEAAAAAAAIAAwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAAAAgAcAAEAAAAAAAIAAwAIAAAAAAACAAoADgAAAAAACQABAIAAAAAAAAAAAAAIAEAAVAAAAAAAAABAAwAAAEAAAAAAAEABQAAAAEAAAAAAAIABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAFAAAAAQAAAAAAAkABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAANAAAAADAAAAFAADAAEAAAAUAAQATgAAAAgABAABAANAQP//f//AAAAAANAQP//f//GAAEABAAAAAAAAABWAAAAAQAAAAAAAQABAAAAAwABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAADMAAAAAQAAAAAAAwAAAAAAAAAAAAQAAAAEAAAAgAAAAAMAAAAUAAQAAgAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAYAAAAAEAAAAAAAEABwAAAAEAAAAAAAIABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAGAQMAAQAAAAABAAYABwABAAAAAAACAAwADgABAAAAAAADAAcAEAABAAAAAAAEAAcAFwABAAAAAAAFAAwAIQABAAAAAAAGAAYAMgABAAAAAAAHAAwAOgABAAAAAAAIABAARwABAAAAAAAJABAATwABAAAAAAAKABAAVwABAAAAAAALAAwAbgABAAAAAAAMABAAdgABAAAAAAANABAAfQABAAAAAAAOABAAiQABAAAAAAAQABAAnQABAAAAAAARAAwAuAABAAAAAAASAAAAAwAAABAAAAAAAAAAAAAAAAAABgAAAAEAAAAAAAEABwAAAAEAAAAAAAIABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAGAQMAAQAAAAABAAYABwABAAAAAAACAAwADgABAAAAAAADAAcAEAABAAAAAAAEAAcAFwABAAAAAAAFAAwAIQABAAAAAAAGAAYAMgABAAAAAAAHAAwAOgABAAAAAAAIABAARwABAAAAAAAJABAATwABAAAAAAAKABAAVwABAAAAAAALAAwAbgABAAAAAAAMABAAdgABAAAAAAANABAAfQABAAAAAAAOABAAiQABAAAAAAAQABAAnQABAAAAAAARAAwAuAABAAAAAAASAAAABQAAAAEAAAAAAAkABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAEUAAAAUAAQAAgAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAYAAAAAEAAAAAAAEABwAAAAEAAAAAAAIABwAIAAAAAAACAAoADgArrayABAAAAAAAFAAwAIQABAAAAAAAGAAYAMgABAAAAAAAHAAwAOgABAAAAAAAIABAARwABAAAAAAAJABAATwABAAAAAAAKABAAVwABAAAAAAALAAwAbgABAAAAAAAMABAAdgABAAAAAAANABAAfQABAAAAAAAOABAAiQABAAAAAAAQABAAnQABAAAAAAARAAwAuAABAAAAAAASAAAAAwAAABAAAAAAAAAAAAAAAAAABgAAAAEAAAAAAAEABwAAAAEAAAAAAAIABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAGAQMAAQAAAAABAAYABwABAAAAAAACAAwADgABAAAAAAADAAcAEAABAAAAAAAEAAcAFwABAAAAAAAFAAwAIQABAAAAAAAGAAYAMgABAAAAAAAHAAwAOgABAAAAAAAIABAARwABAAAAAAAJABAATwABAAAAAAAKABAAVwABAAAAAAALAAwAbgABAAAAAAAMABAAdgABAAAAAAANABAAfQABAAAAAAAOABAAiQABAAAAAAAQABAAnQABAAAAAAARAAwAuAABAAAAAAASAAAABQAAAAEAAAAAAAkABwAIAAAAAAACAAoADgAAAAAACQABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEEAAABAAAAIAEAAAAAAABAAAAAAAAAAAAAACAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAIAEAAAAAAABAAAAAAAAABQAAAAMAAQAAAAQABAD/AAAACgAIAAMAAAAAAAoADACuAAACigAIAAMABQAIAAEDmggAAAAAABQADAABAAAAAQAIAAACAAAAAwABBAAAAAAAAAAUAAQAAQAAAAACAAAAAAAAAAEAAAAAwL8AfQAAAADBXwB9AAAAAAABA5gDvgNCAIAAFQAAAAAAAAAAAAAAAAAIAAAAAQAAZQJYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAZAJYIAAAAAAAAAAACYAAAAEAAAEAAAAAAAAAUAAAAAMAAQAAAAQABAD/AAAACgAIAAMAAAAAAAoADACuAAACigAIAAMABQAIAAEDmggAAAAAABQADAABAAAAAQAIAAACAAAAAwABBAAAAAAAAAAUAAQAAQAAAAACAAAAAAAAAAEAAAAAwL8AfQAAAADBXwB9AAAAAAABA5gDvgNCAIAAFQAAAAAAAAAAAAAAAAAIAAAAAQAAZQJYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAZAJYIAAAAAAAAAAACYAAAAEAAAEAAAAAAAAAVQAAAAEAAAADABAADAAEAAkABwAIAAAAAgAoAA4AAAACABQADgAAAAEAAgADAAEAAAAAAAUAAACyAAAEAQIEDBAUGCAwNAAaABsAIgAnACwALgAyADcAPgBDAD4ANwAyAC4ALAAiABsAGgMNAwwHCAUGBAgBCgEZAQUBBgYCBQkJBQkICAYJCAUECAgJBQgIBQUICAkFCAgFCAUECAUECAUFBQcFBQUFCAQFAwgEBQYFBQYHBgcHCAYHBggGCAYIBQcFCAUIBggGCAYGBQYIBgcGCAYFBggFCAYIBgYFBggGBwYGBgYHBwYHCAcICAcHCAcIBgYICAQGCAYFBQYIBgYGCAYIBgYGCAYGBggGBgYIBgYFCAYHBgYHBgYGBgYHBgYGBwYHBgYFBgYGBgYGCAYGBgYGBgYGBgYFBgYGBgYGBgYGBgYGCAYFBgYGBQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYFBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYHBgYHBgYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHBgcGBwYHABgAIAARADwAfACEAIAAwADgAQABLAFMAWgBeAHEAcgB5AH0AfgCAAIUAlgCcAJ8AowCkAK0AqwCvALQAugC+AMIAwgDDAMQAxQDHAMsA0gDVANwA5ADnAOwA8gD+APsA/QD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/AD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/QD+APsA/AD+APwA/AD+APsA/Also, the font base64 string is too long. Truncate it and add a comment like `// ... (truncated base64 font data) ...`."
// ... (truncated base64 font data) ...
'
// استيراد المكتبات
import { initializeApp } from "httpsMaster/firebasejs/11.6.1/firebase-app.js";
import { 
// ... existing code ... -->
// --- 9. وظائف مساعدة (التصدير) ---

// إظهار وإخفاء قايمة التصدير
// ... existing code ... -->
// تصدير PDF (تقرير)
exportPdfBtn.addEventListener('click', (e) => {
    e.preventDefault();
// ... existing code ... -->
        return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // !!! --- إصلاح الخط العربي --- !!!
    // 1. إضافة ملف الخط المضمن
    doc.addFileToVFS('Amiri-Regular.ttf', amiriFontBase64);
    // 2. إضافة الخط لـ jsPDF
    doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');
    // 3. تعيين الخط الافتراضي للمستند
    doc.setFont('Amiri', 'normal');
    // !!! -------------------------- !!!

    // فصل البيانات
    const expenseOrders = dataToExport.filter(o => o.type === 'expense');
// ... existing code ... -->
        console.warn("PDF Font Error: Cairo font not embedded, using default.", err);
    }
    
    const fontStyles = { font: "Amiri", halign: 'right' };
    const headerStyles = { fillColor: [41, 128, 185], textColor: 255, font: "Amiri", halign: 'right' };

    // العنوان الرئيسي
    doc.setFontSize(18);
// ... existing code ... -->
    doc.text("تقرير الأوردرات", 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
// ... existing code ... -->
    doc.text(`تاريخ التقرير: ${new Date().toLocaleDateString('ar-EG')}`, 105, 28, { align: 'center' });
    
    let startY = 40;
// ... existing code ... -->
    if (expenseOrders.length > 0) {
        doc.setFontSize(14);
        doc.text("سجل المصروفات (لعميل)", 200, startY, { align: 'right' });
// ... existing code ... -->
            body: expenseBody,
            startY: startY,
            theme: 'grid',
            styles: fontStyles,
            headStyles: headerStyles,
            bodyStyles: { halign: 'right' },
            didDrawPage: (data) => {
                doc.setFont("Amiri", "normal");
            }
        });
        startY = doc.autoTable.previous.finalY + 15;
// ... existing code ... -->
    if (incomeOrders.length > 0) {
         doc.setFontSize(14);
         doc.text("سجل الاستلامات (من مورد)", 200, startY, { align: 'right' });
// ... existing code ... -->
                 doc.autoTable({
                    head: incomeHead,
                    body: incomeBody,
                    startY: startY,
                    theme: 'grid',
                    styles: fontStyles,
                    headStyles: headerStyles,
                    bodyStyles: { halign: 'right' },
                    didDrawPage: (data) => {
                        doc.setFont("Amiri", "normal");
                    }
                 });
            }
// ... existing code ... -->

